Update getting-started.md ; need to npm install react-native after changing to project directory
need react-native installed otherwise code:
```
npx react-native-windows-init --overwrite
```
has error:
Reading project name from package.json...
Reading react-native version from node_modules...
Cannot find module 'react-native/package.json'