Update CI pipeline to use windows-2022 image (#1096)
## Description
Changed the build agent image in Azure Pipelines from windows-latest to
windows-2022 for improved compatibility and consistency.

### Why
windows-latest is breaking the CI pipelines for sample apps and we need
to update sample apps.

CI Error:
<issue_description> Utilization: 100.0 Average Utilization: 100.0
✖ Building Solution

Build failed with message C:\Program Files\Microsoft Visual
Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.WindowsSDK.targets(46,5):
error MSB8036: The Windows SDK version 10.0.22621.0 was not found.
Install the required version of Windows SDK or change the SDK version in
the project property pages or by right-clicking the solution and
selecting "Retarget solution".
[D:\a\src\windows\CalculatorFabric\CalculatorFabric.vcxproj]. Check your
build configuration.
✖ Build failed with message C:\Program Files\Microsoft Visual
Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.WindowsSDK.targets(46,5):
error MSB8036: The Windows SDK version 10.0.22621.0 was not found.
Install the required version of Windows SDK or change the SDK version in
the project property pages or by right-clicking the solution and
selecting "Retarget solution".
[D:\a\src\windows\CalculatorFabric\CalculatorFabric.vcxproj]. Check your
build configuration.
It is possible your installation is missing required software
dependencies. Dependencies can be automatically installed by running
D:\a\src\node_modules\react-native-windows\scripts\rnw-dependencies.ps1
from an elevated PowerShell prompt.
For more information, go to http://aka.ms/rnw-deps
✖ It is possible your installation is missing required software
dependencies. Dependencies can be automatically installed by running
D:\a\src\node_modules\react-native-windows\scripts\rnw-dependencies.ps1
from an elevated PowerShell prompt.
For more information, go to http://aka.ms/rnw-deps
Command failed with error MSBuildError: C:\Program Files\Microsoft
Visual
Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.WindowsSDK.targets(46,5):
error MSB8036: The Windows SDK version 10.0.22621.0 was not found.
Install the required version of Windows SDK or change the SDK version in
the project property pages or by right-clicking the solution and
selecting "Retarget solution".
[D:\a\src\windows\CalculatorFabric\CalculatorFabric.vcxproj]
Error: Process completed with exit code 1.</issue_description>

###### Microsoft Reviewers: [Open in
CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows-samples/pull/1096)